### ISSUE TITLE
feature request: allow max retries to be specified

### ISSUE THREAD

**Issue by paultanger** [mddub/everytrail_export#1]
Hey man!  This is pretty sweet!  Thanks for putting this together.  Because the website is getting slower and slower, you might want to consider adding a command line option to specify MAX_RETRIES.  I had to change MAX_RETRIES = 10 in order to get my trips downloaded because it kept errorring out when it only tried 3 times.  Anyways, just an idea.

**Comment by mddub** [comment]
Great idea, thanks for the feature request! I guess it's gotten worse since my testing with 3 retries :(

I've implemented this in 66e3ea0535d496d3baa9d791bbf65e2799d7639d.
